---
repos:
  - repo: https://github.com/PyCQA/bandit
    rev: '1.9.2'
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
          - --configfile=.bandit.yaml
        files: ^custom_components/hilo/.+\.py$
  - repo: https://github.com/python/black
    rev: 25.12.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        language_version: python3
        files: ^custom_components/hilo/.+\.py$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --help
          - -S "./.*,*.json,README.md"
          - --quiet-level=5
          - -L ba,hass,que,bord
        exclude_types: [json]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.5.0
          - pydocstyle==5.0.1
        files: ^custom_components/hilo/.+\.py$
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        additional_dependencies:
          - toml
        files: ^custom_components/hilo/.+\.py$
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.920
#    hooks:
#      - id: mypy
#        files: ^pyhilo/.+\.py$
#        additional_dependencies:
#          - types-python-dateutil==2.8.0

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
        # Exclude .devcontainer.json and .vscode since it uses JSONC
        exclude: (.vscode|.devcontainer)
      - id: no-commit-to-branch
        args:
          - --branch=main
#  - repo: https://github.com/PyCQA/pydocstyle
#    rev: 5.0.2
#    hooks:
#      - id: pydocstyle
#        files: ^custom_components/hilo/.+\.py$
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: shellcheck
        files: ^script/.+
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        name: gitlint
        language: python
        entry: gitlint
        args: [--staged, --msg-filename]
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
